<img src="img/usmlogo.png" style="float:right;height:100px">
<img src="img/dilogo.png" style="float:left;height:100px">
<center>
    <h1> Laboratorio 3 </h1>
    <h2> Profesor: Ricardo Ñanculef </h2>
    <h3> Ayudante: Gabriel Ortega </h3>
    <h4> Alumno ; Rol ; Malla </h4>
    <h4> Alumno2 ; Rol ; Malla </h4>
</center>
<p>
<center><h4>_Fecha_</h4></center>
</p>

## Instrucciones


La modalidad de trabajo será mediante el uso de jupyter notebook. El notebook debe ser desarrollado en parejas o individual pero solamente una de esas modalidades (Pueden cambiar de compañero o modalidad en cada laboratorio). Este laboratorio debe ser entregado a más tardar el día Viernes 30 de Noviembre, no se aceptan entregas enviadas al correo del ayudante.

La **modalidad de entrega será un archivo Apellido1_Apellido2_Lab2.zip/.tar.gz/rar** que contenga un notebook que incluya todas las preguntas con sus respectivas respuestas + un README que indique la forma correcta de ejecutar su notebook. Este notebook presenta ciertas preguntas marcadas con **O:** que indican que para los alumnos de malla nueva es opcional, pero obligatoria para los alumnos de malla vieja. En el caso de haber una pareja con un integrante de malla nueva y uno de malla vieja, se considera malla vieja. El laboratorio puede ser trabajado tanto en lenguaje R como en lenguaje python (para los que usen python 2.X, absténganse a las consecuencias). Lea bien el enunciado.

Su notebook debe incluir un encabezado como el presente en este notebook (Si utilizará las imagenes recuerde adjuntar la carpeta de imagenes o borrarlas del markdown), **para la malla debe colocar INF-280 o ILI-280** según corresponda (no ponga otras cosas o se descontará). 

**Cualquier copia detectada implicará reprobación del laboratorio con nota 0 (lo que implica reprobar el ramo con nota 0) además de la notificación correspondiente al Profesor.** 

## 1. Gradiente Ascendente (35p)

> Spoiler de machine learning :) 

La técnica de gradiente ascendente (o descendente) es un algoritmo iterativo para hallar los óptimos de una función diferenciable, en especial cuando los óptimos de esta resultan difíciles de obtener analíticamente. La regla que sigue este algoritmo ascendente es la siguiente:

$$\theta_{n+1} = \theta_{n} + \eta \cdot \nabla F(\theta_{n})$$

Donde $\nabla F$ es la derivada de la función que nos interesa optimizar, $\theta$ el estimador que nos interesa determinar y $\eta$ un coeficiente llamado "Factor de aprendizaje" $\in [0,1]$. Este algoritmo se detiene una vez realizada una cierta cantidad de iteraciones o una vez que la variación es más pequeña que un umbral dado.

En este caso se trabajará con una función cuyo óptimo analítico puede obtenerse fácilmente para términos de comparación. Se trabajará con una distribución de Poisson de $\lambda$ desconocido (poisson.csv) y la función de log-verosimilitud. Se sabe que la función de la distribución de poisson es:

\begin{aligned}
\frac{\lambda ^{x}\cdot e^{-\lambda}}{x!}
\end{aligned}

>a) Plantee las ecuaciones de log-verosimilitud y la primera y segunda derivada de esta función para determinar el máximo verosímil de $\lambda$ ¿En base a las ecuaciones, se puede decir que se obtendrá un máximo? 

>b) Determine el máximo verosímil de $\lambda$ analítico (resolviendo las ecuaciones correspondientes)

>c) Utilizando el método de gradiente ascendente determine el valor del máximo verosímil de $\lambda$ y compare con lo obtenido en b). Esto implica que debe elegir un número de iteraciones o un umbral (o ambos), elegir un factor de aprendizaje y un $\lambda_{0} = 0$. **Si no responde esta pregunta anula todo el puntaje de esta sección.**

*Hint: use un factor de aprendizaje pequeño*

>d) Utilizando el método de c) grafique el valor de $\lambda$ en cada iteración. ¿Qué observa a partir de este gráfico?

> **O** e) Repita d) pero utilizando distintos valores de factor de aprendizaje $\eta \in [0,1]$ y comente lo que sucede.

**Bonus (opcional para todos), bonificación de hasta un 10% en su nota de este laboratorio** 

> f) Si quisiera resolver este problema como gradiente descendente ¿Cómo deberían ser las ecuaciones involucradas? Escríbalas todas y además explique en qué consiste la regla que aplica el gradiente.

## 2. Método de la Función Inversa (15p)

El teorema de la función inversa permite generar variables aleatorias continuas con una función de distribución $F(x)$ a partir de la inversa $F^{-1}(x)$. Donde los valores generados en la función inversa están regidos por una distribución uniforme $u \sim U(0,1)$. 

En esta sección se trabajará con la distribución Weibull, cuya función de densidad de probabilidad está dada por:

\begin{aligned}
Weibull(\alpha,\beta) = \frac{\alpha}{\beta^{\alpha}}x^{\alpha -1}\cdot exp \left( \frac{-x}{\beta}\right)^{\alpha}
\end{aligned}

>a) Calcule la función de densidad acumulada. Determine si esta función es invertible o no

$F(x) = 1 - e^{-(\frac{x}{\alpha })^{\beta }}$

Si es invertible, ya que 

$F(x1) = F(x2)$ ssi $x1 = x2$ y F(x) esta definida para todo valor de x.

>b) Obtener la función inversa despejando la variable X. La distribución Weibull a trabajar tiene parámetros $\alpha = 7$ y $\beta = 2$.

$x = 7\sqrt{-\ln \left(1-x\right)}$

>c) Genere 10000 valores $u\sim U(0,1)$ y reemplácelos en la función inversa que obtuvo. Luego proceda a graficar la densidad de los resultados obtenidos del reemplazo en su función inversa.

In [92]:
data = runif(10000, 0, 1)


valores = vector()
for(i in 1:10000){
    valores[i] = 7*(-log(1-data[i]))**0.5
    }


>d) Genere una distribución Weibull de tamaño 10000 con los mismos $\alpha$ y $\beta$ que la trabajada anteriormente, grafique la densidad de los valores generados y concluya respecto a lo observado mencionando, además, una ventaja del método de la función 
inversa.

In [111]:
library(dplyr)

wei = rweibull(10000, 7, 2)
df_wei = data.frame(wei, valores)


# By default, the x ranges fill the scale
ggplot(df_wei, aes(x = wei, fill = density)) +
  geom_density(col = valores, alpha = 0.35) +
  scale_x_continuous(limits = c(0, 24)) +
  coord_cartesian(ylim = c(0, 0.3))


Don't know how to automatically pick scale for object of type function. Defaulting to continuous.
ERROR while rich displaying an object: Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, : arguments imply differing number of rows: 10000, 0

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     

## 3. Teorema del Límite Central (50p)

#### 3.1 TLC Univariado (20p)

El teorema del límite central es uno de los postulados más importantes de estadística. En esta sección se procederá a comprobarlo en su forma clásica. 

Sea $x_{1},x_{2},....,x_{n}$ una muestra aleatoria de tamaño $n$ IID extraidas de una distribución con valor esperado $\mu$ y varianza finita $\sigma^{2}$. Si calculamos la media muestral: 

$$ \bar{X}_{n} = \frac{\sum x_{i}}{n}$$

Y repetimos este proceso una gran cantidad de veces $(P)$ tendremos una distribución de las medias de las muestras (*Sample mean distribution*). El TLC establece que, si el número de repeticiones es lo suficientemente grande: 

$$ \bar{X} \sim N\left(\mu,\sqrt{\frac{\sigma^{2}}{n}}\right)$$ 

Trabajará con una variable aleatoria discreta cuyas probabilidades están dadas por la siguiente tabla:

| Valor | Probabilidad |
|:-----:|:------------:|
|   1   |      0.1     |
|   2   |      0.2     |
|   5   |     0.05     |
|   6   |     0.05     |
|   7   |      0.4     |
|   9   |     0.15     |
|   10  |     0.05     |


> **O** a) Grafique la densidad de esta distribución y comente lo que observa. ¿Le parece normal (refiriéndose a la distribución normal)?

>b) Determine el valor esperado de esta distribución y la varianza 

In [5]:
valor_esperado = 1*0.1 + 2*0.2 + 5*0.05 + 6 * 0.05 + 7 * 0.04 + 9 * 0.15 + 10*0.05
print("Valor Esperado")
valor_esperado

e_x_2 = 1*0.1 + 4*0.2 + 25*0.05 + 36 * 0.05 + 49 * 0.04 + 81 * 0.15 + 100*0.05
e_2_x = valor_esperado**2

varianza = e_x_2 - e_2_x
print("Varianza")
varianza

[1] "Valor Esperado"


[1] 3.18

[1] "Varianza"


[1] 12.9476

$\mu$ = 3.18


$\sigma^{2}$ = 12.9476

El Valor Esperado de la tabla es 3.18 y la Varianza es 12.9476

>c) Con $P = 10000$ calcule la media de muestras de tamaño : $n \in[2,10,30,100,1000]$ 

Código Hint: (Que puede implementar de otra manera si le acomoda)

**Python**
```python
import numpy as np
tamano_n = np.array([]) #para cada n
for i in range(P):
    tamano_n = np.append(tamano_n,np.mean(muestra_de_tamano_n))
```

**R**
```r
tamano_n = vector() #para cada n
for(i in 1:P){
    tamano_n[i] = mean(muestra_de_tamano_n)
    }
```

In [22]:
tamano_2 = vector() #para cada n
P = 1000
for(i in 1:P){
    tamano_2[i] = mean(sample(1:10,2,replace=T))
    }

cat("Tamaño 2, mediana: ",mean(tamano_2), "\n")


tamano_10 = vector() #para cada n
P = 1000
for(i in 1:P){
    tamano_10[i] = mean(sample(1:10,10,replace=T))
    }

cat("Tamaño 10, mediana: ",mean(tamano_10), "\n")


tamano_30 = vector() #para cada n
P = 1000
for(i in 1:P){
    tamano_30[i] = mean(sample(1:10,30,replace=T))
    }

cat("Tamaño 30, mediana: ",mean(tamano_30), "\n")


tamano_100 = vector() #para cada n
P = 1000
for(i in 1:P){
    tamano_100[i] = mean(sample(1:10,100,replace=T))
    }

cat("Tamaño 100, mediana: ",mean(tamano_100), "\n")


tamano_1000 = vector() #para cada n
P = 1000
for(i in 1:P){
    tamano_1000[i] = mean(sample(1:10,1000,replace=T))
    }

cat("Tamaño 1000, mediana: ",mean(tamano_1000), "\n")



Tamaño 2, mediana:  5.522 
Tamaño 10, mediana:  5.4682 
Tamaño 30, mediana:  5.517967 
Tamaño 100, mediana:  5.50287 
Tamaño 1000, mediana:  5.494243 


Tamaño 2, mediana:  5.436

Tamaño 10, mediana:  5.5265 

Tamaño 30, mediana:  5.494533 

Tamaño 100, mediana:  5.49805 

Tamaño 1000, mediana:  5.503083 

>d) **O:** Explique el concepto de *Skewness* y *Kurtosis* 

>e) Para cada vector de datos haga un histograma incluyendo la curva de densidad, además de indicar la media, varianza, skewness y kurtosis de los datos. Comente lo que sucede con cada campo comparando los gráficos y en base a lo que enuncia el TLC.

Kurtosis y Skewness: python $\rightarrow$ scipy | R $\rightarrow$ e1071


In [27]:
install.packages("moments")


Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)


In [59]:
library(ggplot2)

library(moments)

tamano_2_frame = data.frame(tamano_2)

cat("Varianza (n=2)", var(tamano_2), "\n")
cat("Media    (n=2)", mean(tamano_2), "\n")
cat("Skewness (n=2)", skewness(tamano_2), "\n")
cat("Kurtosis (n=2)", var(tamano_2_frame), "\n")




ggplot(tamano_2_frame, aes(x = tamano_2)) + 
       geom_histogram(aes(y = ..density..), fill = 'dodgerblue1', alpha = 0.8, binwidth=.5) + 
       geom_density(colour = 'firebrick1') + xlab(expression(bold('Muestras Simuladas n=2'))) + 
       ylab(expression(bold('Densidad')))





Varianza (n=2) 4.298815 
Media    (n=2) 5.522 
Skewness (n=2) 0.001635047 
Kurtosis (n=2) 4.298815 


In [68]:
tamano_10_frame = data.frame(tamano_10)

cat("Varianza (n=10)", var(tamano_10), "\n")
cat("Media    (n=10)", mean(tamano_10), "\n")
cat("Skewness (n=10)", skewness(tamano_10), "\n")
cat("Kurtosis (n=10)", var(tamano_10_frame), "\n")

ggplot(tamano_10_frame, aes(x = tamano_10)) + 
       geom_histogram(aes(y = ..density..), fill = 'dodgerblue1', alpha = 0.8, binwidth=.5) + 
       geom_density(colour = 'firebrick1') + xlab(expression(bold('Muestras Simuladas n=10'))) + 
       ylab(expression(bold('Densidad')))




Varianza (n=10) 0.8328719 
Media    (n=10) 5.509 
Skewness (n=10) 0.03217262 
Kurtosis (n=10) 0.8328719 


In [67]:
tamano_30_frame = data.frame(tamano_30)

cat("Varianza (n=30)", var(tamano_30), "\n")
cat("Media    (n=30)", mean(tamano_30), "\n")
cat("Skewness (n=30)", skewness(tamano_30), "\n")
cat("Kurtosis (n=30)", var(tamano_30_frame), "\n")

ggplot(tamano_30_frame, aes(x = tamano_30)) + 
       geom_histogram(aes(y = ..density..), fill = 'dodgerblue1', alpha = 0.8, binwidth=.5) + 
       geom_density(colour = 'firebrick1') + xlab(expression(bold('Muestras Simuladas n=30'))) + 
       ylab(expression(bold('Densidad')))






Varianza (n=30) 0.2648825 
Media    (n=30) 5.488067 
Skewness (n=30) 0.06154981 
Kurtosis (n=30) 0.2648825 


In [24]:
tamano_100_frame = data.frame(tamano_100)

cat("Varianza (n=100)", var(tamano_100), "\n")
cat("Media    (n=100)", mean(tamano_100), "\n")
cat("Skewness (n=100)", skewness(tamano_100), "\n")
cat("Kurtosis (n=100)", var(tamano_100_frame), "\n")


ggplot(tamano_100_frame, aes(x = tamano_100)) + 
       geom_histogram(aes(y = ..density..), fill = 'dodgerblue1', alpha = 0.8, binwidth=.5) + 
       geom_density(colour = 'firebrick1') + xlab(expression(bold('Muestras Simuladas n=100'))) + 
       ylab(expression(bold('Densidad')))




Varianza (n=100) 0.08636343 
Media    (n=100) 5.50287 


ERROR: Error in skewness(tamano_100): could not find function "skewness"


In [31]:
tamano_1000_frame = data.frame(tamano_1000)

cat("Varianza (n=1000)", var(tamano_1000), "\n")
cat("Media    (n=1000)", mean(tamano_1000), "\n")
cat("Skewness (n=1000)", skewness(tamano_1000), "\n")
cat("Kurtosis (n=1000)", var(tamano_1000_frame), "\n")

ggplot(tamano_1000_frame, aes(x = tamano_1000)) + 
       geom_histogram(aes(y = ..density..), fill = 'dodgerblue1', alpha = 0.8, binwidth=.5) + 
       geom_density(colour = 'firebrick1') + xlab(expression(bold('Muestras Simuladas n=1000'))) + 
       ylab(expression(bold('Densidad')))

Varianza (n=1000) 0.008952637 
Media    (n=1000) 5.494243 
Skewness (n=1000) -0.04333098 
Kurtosis (n=1000) 0.008952637 


Mientras P es más grande, la dispersión de los datos es menor, aumentando la densidad de los datos en torno a su media.

#### 3.2 TLC Multivariado (30p) 

Si en este caso se cuenta con una matriz de datos (una tabla con mas de 1 atributo) y las filas de esta matriz representan una muestra de una variable aleatoria multivariada $\bar{\chi}$ con $E(\,\bar{\chi}) = \mu$ y $Cov(\,\bar{\chi}) = \sum$ entonces la distribución asintótica de $\bar{\chi}$ es una normal multivariada con vector de medias $\mu$ y matriz de covarianza $\frac{1}{N}\cdot \sum$. Además de que se espera que la proyección en cada eje sea normal.

Si hay tres variables involucradas: 

$$X \sim Distribución\, en\; 3.1$$

$$Y \sim Poi(\lambda = 10)$$

$$Z \sim U(1,100)$$

>a) Genere un dataset que cumpla las distribuciones mencionadas anteriormente con 20000 filas

In [35]:
X <- rnorm(20000, 3.18, 12.9476)
Y <- rpois(20000, 10)
Z <- runif(20000, 1, 100)


dataset = data.frame(X, Y, Z)

dataset



X            Y   Z        
1     -14.43761174  3  88.855150
2      -3.85860223  7  40.018036
3       0.37724719  5  63.727389
4      -9.44105559  9  26.564422
5      18.78305362  9  44.392694
6      -2.09809096 15   5.643169
7       0.32321523  9  60.275035
8      -4.11587659 10  25.107295
9      13.65845337 11  49.653826
10     11.71705434  7  19.133383
11     15.19086292 12   7.255497
12      0.66787964 10  85.303741
13     19.65852855  7   4.178718
14      2.81776301 15  57.392347
15     21.44133345  8  60.886985
16      6.34772821  5  16.953650
17     27.68727919 14  58.163961
18     16.04974098 15  55.646501
19     10.24070664  6  74.024352
20     -3.60751176  4  86.780793
21    -10.96266575 10  56.805607
22      0.06217165 10  97.500066
23      2.73826873  8  50.176855
24    -13.16503033 11  87.851703
25      5.08401300 13  49.570862
26      2.32202873  6  52.846241
27      2.37918793 11  95.252625
28    -20.19683993  5  31.856212
29     -5.57790473 12  22.044035
30      6.98960560  6  28.308582
...   ...          ... ...      
19971  17.4561720  11  64.509817
19972   8.8498258  14  34.863335
19973  -0.6184619  10  64.330744
19974  16.3421764   8  77.273630
19975   2.3517414   9   4.770003
19976 -19.8843505   7  78.785677
19977 -22.3081072  14  92.686449
19978  11.5058382  12  34.307799
19979   7.0649943   6  83.949919
19980 -11.9703531  12  75.358418
19981  -5.2535299  13  77.524898
19982  -8.1534473  13  73.634576
19983  22.8512509   7  84.316189
19984   1.7071386  13  59.137166
19985   3.8246921   6  38.355895
19986  -2.4017263  11  40.149627
19987 -22.4035085   6  65.312865
19988 -20.1723410   4  74.834555
19989  11.5236360  13  29.379422
19990  14.9003928  12  84.731996
19991 -11.6485070  15  86.220939
19992  -1.9532035  14   2.199788
19993  11.2227316  12  14.155712
19994 -10.7070128   9  45.506177
19995 -16.7814383   8  15.174918
19996 -13.6895398  11  25.105401
19997   3.0938230  11  59.179512
19998   7.7295413   7  95.685360
19999   5.3626256  14  37.189611
20000   7.0598733  16  89.072212

>b) Obtenga el vector $\vec{\mu}$ y la matriz de covarianza $\sum$ del dataset generado

In [46]:

medias = vector() #para cada n

medias[1] = mean(dataset$X)
medias[2] = mean(dataset$Y)
medias[3] = mean(dataset$Z)
medias


S <- cov(dataset)
S


[1]  3.121863  9.982000 50.633314

X           Y          Z          
X 168.1738523 -0.1890708  -1.3037215
Y  -0.1890708 10.0985809   0.9731274
Z  -1.3037215  0.9731274 808.6045804

# $\vec{\mu}$ 

(3.30668057065034, 9.9917, 50.6714221064263)
# $\sum$



| X | Y           | Z          |             |
|---|-------------|------------|-------------|
| X | 169.5055862 | -0.4203665 | 0.6816698   |
| Y | -0.4203665  | 9.8949259  | -0.5243467  |
| Z | 0.6816698   | -0.5243467 | 814.5565730 |

>c) Con $N = 10000$ y un tamaño muestral de $100$ demuestre lo que enuncia el teorema del límite central multivariado obteniendo un vector $\vec{\mu '}$ y una nueva matriz de covarianza $\sum '$ comparando con lo obtenido en b). También compruebe la proyección en cada eje.

In [44]:

N = 10
for(i in 1:N){
    temp = dataset[sample(nrow(dataset), 100), ]
    temp
}


X            Y   Z        
6886    8.3429839  16  81.895336
1783    2.8822955   9  36.580034
2158   16.1952686  15  73.176888
2356   10.9194436   6  12.838539
5286  -15.7590385   8   5.962732
12672  23.2755655  13  37.953843
10808  18.1822071  12  56.388371
8293    5.5046457   9  76.467307
4421   -8.5791745   9  43.488466
14455  18.0786205  10  39.246352
19723 -15.1128161   9  83.908942
18842  -1.9414529  11  60.393673
19894  -4.0785893  10  85.711656
17227   5.6298723   9  39.438615
9393  -10.2008745   8  96.466302
15058   4.1889062  12  60.151531
4857    6.4898177   8  93.132270
1203   20.7632356  12  12.187896
12514  -2.2722057  15  71.023649
1760    3.5264314   7  98.687736
9367   19.9061915  11  18.160204
3153  -20.0657285  11  30.122117
1718   -3.0437960   9  19.844748
16923 -12.4994567  11   2.451389
3328   -9.4377033   9  36.246732
12439   9.3859223   8  33.350897
16691   0.4296016   9  16.804286
5598    1.7073842  12  14.743914
16291 -14.3598857  12  97.896040
3849   19.5977114  11  87.006629
...   ...          ... ...      
10802  -4.82258192 11  77.645094
10978  -6.87404476  7   2.801626
16802   0.09710036 11  51.531470
7919    7.11974973 10  35.051342
15385   3.56619929 11  99.308206
16712  -3.76004740 11  94.473565
5671    1.26651493 11  74.810469
9110   18.49491965  9  87.362222
11152  -9.96657276 10  90.884953
18822  19.99190925 14  87.218836
4669    5.67614881 11  89.256494
6437   -7.06242183 16  21.316811
888    -2.41040366 11  92.793648
6800    5.28586619  9  27.514304
3180  -17.05762164 13  23.865525
7529    3.27832078 10  23.956628
9602    6.42783636  7  57.621172
7633   19.65148617 22  14.123574
7945    8.78262649  5   6.994757
7691   22.87820979  6  90.224610
653    -5.36599849  8  24.419683
5618   16.02984748 12  15.376777
11097 -12.73347098 10  84.300620
5819  -11.19526702 10  83.071212
18008   1.46054781  9  62.573837
7794    4.07647353  7  97.789605
14894   1.78562747 10  44.332573
3164   18.45273167  6  80.303366
13555   7.23956750 18  78.866581
18281 -13.05676848  9  74.187161

## Reglas del Juego y Comentarios 

+ Celda de código que no ejecute anula la respuesta a todas las preguntas contenidas en esa celda a partir de la falla
+ Errores ortográficos, de redacción y oraciones ambiguas descontarán 1 punto c/u, con límite de 50 puntos. 
+ Dudas solamente hasta el día Martes 27 de Noviembre a las 15:00.
+ Dudas **principalmente** vía moodle, evite otro tipo de medio ya que su duda podría ser la de otro.
+ Cada día de atraso descuenta 25 puntos de la nota final con un máximo de dos días de retraso (después es 0).
+ La versión de R que se usará para revisar es 3.4.3
+ La versión de Python que se usará para revisar es 3.6.5
+ Los alumnos malla nueva que decidan responder las preguntas opcionales (obviando algún bonus para todos) tendrán 1 punto bonus por pregunta correctamente respondida, con un máximo de nota 100.
+ Use cualquier librería que estime conveniente, si requiere de instalación explicitarlo en el README (y bien explicitado).
+ Código comentado para facilitar entendimiento.
+ Sea formal y claro con su respuesta, explique su procedimiento y luego responda. 
+ Intente mantener un carácter científico durante la elaboración de su notebook.
+ Defina bien las secciones de su notebook [Tips para usar Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
